# Generated by Django 3.0.8 on 2020-07-12 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDSlaves', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Enable', models.BooleanField(default=True)),
                ('MAC', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slaveaddres', models.IntegerField(default=4)),
                ('Baudrate', models.CharField(choices=[('9600', '9600'), ('19200', '19200'), ('38400', '38400')], max_length=10)),
                ('Parity', models.CharField(choices=[('E', 'Even'), ('N', 'None'), ('O', 'Odd')], max_length=5)),
                ('Stop', models.IntegerField(default=1)),
                ('Bits', models.IntegerField(default=8)),
                ('Slaves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slaves.Slaves')),
            ],
        ),
    ]
